name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: macOS-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        export GO111MODULE=off; 
        go get -v github.com/therecipe/qt/cmd/... 
        $(go env GOPATH)/bin/qtdeploy test desktop .
